on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test, Prop Tests, Example Tests

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - name: Install stable toolchain & components
        uses: actions/checkout@v2
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run sv1-client-and-server example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin client_and_server -- 60

      - name: interop-test
        run: |
          if [ ${{ matrix.os }} == "ubuntu-latest" ]; then
            ./run.sh 30
          else
            echo "Skipping interop-test on ${{ matrix.os }} - not supported"
          fi
        working-directory: examples/interop-cpp/

      - name: interop-no-cargo-test
        run: |
          if [ ${{ matrix.os }} == "ubuntu-latest" ]; then
            ./run.sh 30
          else
            echo "Skipping interop-test on ${{ matrix.os }} - not supported"
          fi
        working-directory: examples/interop-cpp-no-cargo/

      - name: fuzz tests
        run: |
          if [ ${{ matrix.os }} == "ubuntu-latest" ]; then
            ./run.sh 30
          else
            echo "Skipping fuzz test on ${{ matrix.os }} - not supported"
          fi
        working-directory: utils/buffer/fuzz

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Property based testing
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features prop_test

      - name: Run ping-pong-with-noise example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin ping_pong_with_noise -- 10
      #
      # GitHub Actions hangs on this test. Issue #249
      # - name: Run ping-pong-without-noise example
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: run
      #     args: --bin ping_pong_without_noise -- 10
